name = "survival"
version = "0.1.1"
exports = [
    "srv_gompertz_log_hazard",
    "srv_gompertz_log_hazard",
    "srv_gompertz_log_hazard",
    "srv_log_logistics_log_hazard",
    "srv_log_logistics_log_hazard",
    "srv_log_logistics_log_hazard",
    "srv_makeham_log_hazard",
    "srv_makeham_log_hazard",
    "srv_makeham_log_hazard",
    "srv_makeham_log_hazard",
    "srv_pwe_interval",
    "srv_pwe_exposure",
    "srv_pwe_log_hazard",
    "srv_gompertz_cumulative_hazard",
    "srv_gompertz_cumulative_hazard",
    "srv_gompertz_cumulative_hazard",
    "srv_gompertz_cumulative_hazard",
    "srv_log_logistics_cumulative_hazard",
    "srv_log_logistics_cumulative_hazard",
    "srv_log_logistics_cumulative_hazard",
    "srv_makeham_cumulative_hazard",
    "srv_makeham_cumulative_hazard",
    "srv_makeham_cumulative_hazard",
    "srv_makeham_cumulative_hazard",
    "srv_pwe_cumulative_hazard",
    "srv_gompertz_lpdf",
    "srv_gompertz_lpdf",
    "srv_gompertz_lccdf",
    "srv_gompertz_lccdf",
    "srv_gompertz_loglik",
    "srv_gompertz_loglik",
    "srv_log_logistics_lpdf",
    "srv_log_logistics_lpdf",
    "srv_log_logistics_lccdf",
    "srv_log_logistics_lccdf",
    "srv_log_logistics_loglik",
    "srv_log_logistics_loglik",
    "srv_makeham_lpdf",
    "srv_makeham_lpdf",
    "srv_makeham_lccdf",
    "srv_makeham_lccdf",
    "srv_makeham_loglik",
    "srv_makeham_loglik",
    "srv_pwe_loglik_sum",
    "srv_pwe_loglik",
    "srv_gompertz_survival_curve",
    "srv_gompertz_survival_curve",
    "srv_log_logistics_survival_curve",
    "srv_log_logistics_survival_curve",
    "srv_makeham_survival_curve",
    "srv_makeham_survival_curve",
    "srv_pwe_survival_curve",
    "srv_gompertz_rng",
    "srv_makeham_rng",
    "srv_log_logistics_rng",
    "srv_expm1_div",
    "srv_expm1_div",
    "srv_log1p_div",
]
